### ISSUE TITLE
"Delete Account" resulting in unhandled server error

### ISSUE THREAD

**Issue by KarimGeiger** [bitwarden/core#18]
When I try to delete my account using the WebApp, after entering the correct password it takes a few seconds (30 in my case) after which I get an `unhandled server error has occured` response.

The `masterPasswordHash` gets sent to `https://api.bitwarden.com/accounts/delete` via `POST`, which will then result in a `500` response.

Looks like no data was deleted.

**Comment by kspearrin** [comment]
Thanks for the report. I see the issue. Will work on a fix. In the meantime, if you need your account deleted or data purged out due to a bad import or something, just contact me and I'll do it for you manually.

**Comment by kspearrin** [comment]
Should be resolved with v1.0.3

**Comment by KarimGeiger** [comment]
Thank you!

**Comment by KarimGeiger** [comment]
Hmmm... still not working for me. Is the new version already deployed?

FYI: I have about 700 sites in my vault.

**Comment by kspearrin** [comment]
Yea, it appears this still has some issues for certain users. I'm going to have to keep investigating.

**Comment by kspearrin** [comment]
@KarimGeiger I pushed another possible fix out. Let me know if it works for you now

**Comment by KarimGeiger** [comment]
Great, this seems to work now. Thanks!

**Comment by ingenuitor** [comment]
Hello, I'm also trying to remove my vault data as well and receive an error.  It seems to run for a long time @ 1m 40s before displaying the error.

Errors have occured
An unexpected error has occured.

Maybe it's a simple script timeout, due to parsing size limits?
